/**
 * Catálogo Geográfico Maestro para Zulia / Maracaibo
 * Contiene municipios y sectores/barrios/urbanizaciones estandarizados
 * para autocompletado y análisis geográfico de clientes (sin parroquias).
 */

export interface LocationSector {
  name: string;
  municipality: string;
}

export const ZULIA_MUNICIPALITIES = [
  'Maracaibo',
  'San Francisco',
  'Cabimas',
  'Lagunillas (Ciudad Ojeda)',
  'La Cañada de Urdaneta',
  'Mara',
  'Jesús Enrique Lossada',
  'Machiques de Perijá',
  'Rosario de Perijá (La Villa)',
  'Santa Rita',
  'Miranda (Los Puertos)',
  'Colón (San Carlos)',
  'Baralt (Mene Grande)',
  'Valmore Rodríguez (Bachaquero)',
  'Catatumbo',
  'Jesús María Semprún',
  'Sucre (Caja Seca)',
  'Francisco Javier Pulgar',
  'Guajira',
  'Almirante Padilla'
] as const;

export const MARACAIBO_ZULIA_SECTORS: LocationSector[] = [
  // Maracaibo - Zona Norte, Centro y Este
  { name: '5 de Julio', municipality: 'Maracaibo' },
  { name: 'Bella Vista', municipality: 'Maracaibo' },
  { name: 'Delicias Norte', municipality: 'Maracaibo' },
  { name: 'Delicias Centro', municipality: 'Maracaibo' },
  { name: 'Delicias Sur', municipality: 'Maracaibo' },
  { name: 'El Milagro', municipality: 'Maracaibo' },
  { name: 'La Lago', municipality: 'Maracaibo' },
  { name: 'La Virginia', municipality: 'Maracaibo' },
  { name: 'Tierra Negra', municipality: 'Maracaibo' },
  { name: 'Zapara', municipality: 'Maracaibo' },
  { name: 'Monte Bello', municipality: 'Maracaibo' },
  { name: 'La Picola', municipality: 'Maracaibo' },
  { name: 'El Rosal', municipality: 'Maracaibo' },
  { name: 'Las Mercedes', municipality: 'Maracaibo' },
  { name: 'Don Bosco', municipality: 'Maracaibo' },
  { name: 'Canta Claro', municipality: 'Maracaibo' },
  { name: '18 de Octubre', municipality: 'Maracaibo' },
  { name: 'Urb. San Jacinto', municipality: 'Maracaibo' },
  { name: 'Canchancha', municipality: 'Maracaibo' },
  { name: 'El Naranjal', municipality: 'Maracaibo' },
  { name: 'La Trinidad', municipality: 'Maracaibo' },
  { name: 'Urb. La Floresta', municipality: 'Maracaibo' },
  { name: 'Barrio Teotiste de Gallegos', municipality: 'Maracaibo' },
  { name: 'Santa Rosa de Agua', municipality: 'Maracaibo' },
  { name: 'Capitán Chico', municipality: 'Maracaibo' },
  { name: 'Puntica de Piedra', municipality: 'Maracaibo' },
  { name: 'Milagro Norte', municipality: 'Maracaibo' },
  { name: 'Cerros de Marín', municipality: 'Maracaibo' },
  { name: 'Veritas', municipality: 'Maracaibo' },
  { name: 'Valle Frío', municipality: 'Maracaibo' },
  { name: 'Santa Lucía', municipality: 'Maracaibo' },
  { name: 'El Empedrao', municipality: 'Maracaibo' },
  { name: 'Casco Central / Centro', municipality: 'Maracaibo' },
  { name: 'El Tránsito', municipality: 'Maracaibo' },

  // Maracaibo - Zona Oeste y Noroeste
  { name: 'La Limpia', municipality: 'Maracaibo' },
  { name: 'La Fusta', municipality: 'Maracaibo' },
  { name: 'Curva de Molina', municipality: 'Maracaibo' },
  { name: 'La Rotaria', municipality: 'Maracaibo' },
  { name: 'Los Olivos', municipality: 'Maracaibo' },
  { name: 'La Victoria', municipality: 'Maracaibo' },
  { name: 'Panamericano', municipality: 'Maracaibo' },
  { name: 'Cuatricentenario', municipality: 'Maracaibo' },
  { name: 'Raúl Leoni', municipality: 'Maracaibo' },
  { name: 'Loma Linda', municipality: 'Maracaibo' },
  { name: 'Amparo', municipality: 'Maracaibo' },
  { name: 'Gallo Verde', municipality: 'Maracaibo' },
  { name: 'Barrio Bolívar', municipality: 'Maracaibo' },
  { name: 'Barrio Raúl Leoni', municipality: 'Maracaibo' },
  { name: 'Barrio Francisco de Miranda', municipality: 'Maracaibo' },
  { name: 'Barrio Santa Inés', municipality: 'Maracaibo' },
  { name: 'San José', municipality: 'Maracaibo' },
  { name: 'Indio Mara', municipality: 'Maracaibo' },
  { name: 'Santa María', municipality: 'Maracaibo' },
  { name: 'Paraíso', municipality: 'Maracaibo' },
  { name: 'San Rafael', municipality: 'Maracaibo' },
  { name: 'La Rinconada', municipality: 'Maracaibo' },
  { name: 'Playa Grande', municipality: 'Maracaibo' },
  { name: 'Cumbres de Maracaibo', municipality: 'Maracaibo' },
  { name: 'Altos del Sol Amado', municipality: 'Maracaibo' },
  { name: 'Altos de La Vanega', municipality: 'Maracaibo' },
  { name: 'Barrio Integración Comunal', municipality: 'Maracaibo' },
  { name: 'Barrio El Silencio', municipality: 'Maracaibo' },
  { name: 'Barrio Los Domínguez', municipality: 'Maracaibo' },
  { name: 'Barrio Calendario', municipality: 'Maracaibo' },
  { name: 'Barrio Torito Fernández', municipality: 'Maracaibo' },
  { name: 'Barrio 24 de Julio', municipality: 'Maracaibo' },
  { name: 'Barrio La Curva', municipality: 'Maracaibo' },

  // Maracaibo - Zona Sur & Corredores
  { name: 'Sabaneta', municipality: 'Maracaibo' },
  { name: 'Sabaneta Larga', municipality: 'Maracaibo' },
  { name: 'Pomona', municipality: 'Maracaibo' },
  { name: 'Los Haticos', municipality: 'Maracaibo' },
  { name: 'Haticos por Arriba', municipality: 'Maracaibo' },
  { name: 'Haticos por Abajo', municipality: 'Maracaibo' },
  { name: 'La Arreaga', municipality: 'Maracaibo' },
  { name: 'El Guayabal', municipality: 'Maracaibo' },
  { name: 'Los Estanques', municipality: 'Maracaibo' },
  { name: 'Urb. Urdaneta', municipality: 'Maracaibo' },
  { name: 'Urb. Sucre', municipality: 'Maracaibo' },
  { name: 'Barrio Los Andes', municipality: 'Maracaibo' },
  { name: 'Barrio San Pedro', municipality: 'Maracaibo' },
  { name: 'Barrio Zulia', municipality: 'Maracaibo' },
  { name: 'Kilómetro 4', municipality: 'Maracaibo' },

  // San Francisco
  { name: 'La Coromoto', municipality: 'San Francisco' },
  { name: 'Sierra Maestra', municipality: 'San Francisco' },
  { name: 'San Francisco Centro', municipality: 'San Francisco' },
  { name: 'Urb. San Felipe', municipality: 'San Francisco' },
  { name: 'El Manzanillo', municipality: 'San Francisco' },
  { name: 'Urb. El Soler', municipality: 'San Francisco' },
  { name: 'La Popular', municipality: 'San Francisco' },
  { name: 'El Caujaro', municipality: 'San Francisco' },
  { name: 'Fundabarrios', municipality: 'San Francisco' },
  { name: 'Bajo Grande', municipality: 'San Francisco' },
  { name: 'Urb. Banesco', municipality: 'San Francisco' },
  { name: 'Urb. Villa Chinita', municipality: 'San Francisco' },
  { name: 'Zona Industrial San Francisco', municipality: 'San Francisco' },
  { name: 'Barrio Bicentenario Sur', municipality: 'San Francisco' },

  // Costa Oriental del Lago & Otros Municipios
  { name: 'Centro de Cabimas', municipality: 'Cabimas' },
  { name: 'Las Cabillas', municipality: 'Cabimas' },
  { name: 'Ambrosio', municipality: 'Cabimas' },
  { name: 'La Rosa', municipality: 'Cabimas' },
  { name: 'Miraflores', municipality: 'Cabimas' },
  { name: 'Centro de Ciudad Ojeda', municipality: 'Lagunillas (Ciudad Ojeda)' },
  { name: 'Las Morochas', municipality: 'Lagunillas (Ciudad Ojeda)' },
  { name: 'Tamare', municipality: 'Lagunillas (Ciudad Ojeda)' },
  { name: 'La Concepción', municipality: 'Jesús Enrique Lossada' },
  { name: 'El Carmelo', municipality: 'La Cañada de Urdaneta' },
  { name: 'Chiquinquirá', municipality: 'La Cañada de Urdaneta' },
  { name: 'Santa Cruz de Mara', municipality: 'Mara' },
  { name: 'San Rafael del Moján', municipality: 'Mara' }
];
